#pragma once
#include "glm\glm.hpp"
#include "glm\gtc\matrix_transform.hpp"
#include "GL\glew.h"
#include "GLFW\glfw3.h"
#include <stdio.h>
#include <string.h>
#include <vector>
#include <map>
#include <stdlib.h>
#include <math.h>
#include "VMath.h"
#include <iostream>
#include "ShaderTool.h"
